### ISSUE TITLE
UserWarning when running include_marco.py

### ISSUE THREAD

**Issue by scorbin** [PacktPublishing/Python-Automation-Cookbook#1]
**python3 include_macro.py movies.ods libreoffice_script.py**
/usr/lib/python3.7/zipfile.py:1470: UserWarning: Duplicate name: 'META-INF/manifest.xml'

libreoffice_script.py does not get copied to the ~/.config/libreoffice/4/user

Can I manual create a ~/.config/libreoffice/4/user/Scripts/python dir and copy in the libreoffice_script.py

**Comment by sonam-packt** [comment]
Yes you can try doing that
